version: '3.8'

services:
  postgres:
    image: postgres
    container_name: user_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 9503
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
